exclude: "^docs/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: # arguments to configure black
          - --line-length=88

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args:
          [
            "--profile",
            "black",
            "--skip",
            "__init__.py",
            "--filter-files",
            "--line-length=88",
          ]
