name: pylops
channels:
  - defaults
  - conda-forge
  - numba
dependencies:
  - python>=3.11.0
  - pip
  - numpy>=2.0.0
  - scipy>=1.13.0
  - pyfftw
  - pywavelets
  - sympy
  - pytensor>=2.28.0
  - pymc>=5.21.0
  - matplotlib
  - ipython
  - pytest
  - Sphinx
  - numpydoc
  - numba
  - pre-commit
  - autopep8
  - isort
  - black
  - pip:
    - torch
    - devito
    # - dtcwt (until numpy>=2.0.0 is supported)
    - scikit-fmm
    - spgl1
    - jax
    - pytest-runner
    - setuptools_scm
    - pydata-sphinx-theme
    - pooch
    - sphinx-gallery
    - nbsphinx
    - sphinxemoji
    - image
    - flake8
    - mypy
