name: PyLops Testing (CuPy)

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Print checked code and check environments
        run: |
          ls -lah
          echo $(pwd)
          echo $(which python3)
          echo $(which pip3)
      - name: Set up Python environment and Install dependencies
        run: |
          python3 -m venv pylopsvenv 
          source pylopsvenv/bin/activate 
          echo $(which python3)
          echo $(which pip3)
          python3 -m pip install --upgrade pip setuptools
          pip install flake8 pytest setuptools-scm
          pip install -r requirements-dev-gpu.txt
      - name: Install pylops
        run: |
          source pylopsvenv/bin/activate 
          python3 -m setuptools_scm
          pip install .
      - name: pytest 
        run: |
          export CUPY_PYLOPS=1; export TEST_CUPY_PYLOPS=1; 
          source pylopsvenv/bin/activate 
          pytest
